---
- name: Install and configure auditbeat for Windows 32-bit
  ansible.builtin.import_tasks: "Windows32bit.yml"
  when:
    - ansible_os_family == "Windows"
    - ansible_architecture == "32-bit"

- name: Install and configure auditbeat for Windows 64-bit
  ansible.builtin.import_tasks: "Windows64bit.yml"
  when:
    - ansible_os_family == "Windows"
    - ansible_architecture == "64-bit"

- name: Install and configure auditbeat for RedHat
  ansible.builtin.import_tasks: "RedHat.yml"
  when: ansible_os_family == "RedHat"

- name: Install and configure auditbeat for Debian
  ansible.builtin.import_tasks: "Debian.yml"
  when: ansible_os_family == "Debian"

# Following plays are Linux only specific, all Windows plays are in Windows32bit.yml and Windows64bit.yml
- name: Collect service facts (Linux)
  ansible.builtin.service_facts:
  when:
    - ansible_os_family != "Windows"
#This is necessary, systemd won't allow auditd to be stopped and Ansible has bug when it doesn't use the service binary even if explicitly told
- name: Stop auditd (Linux)
  ansible.builtin.service:
    name: auditd
    state: stopped
  when:
    - ansible_facts.services['auditd'] is defined
    - ansible_os_family != "Windows"
  tags: install

- name: Remove auditd from starting on boot (Linux)
  ansible.builtin.systemd:
    name: auditd
    enabled: false
  when:
    - ansible_facts.services['auditd'] is defined
    - ansible_os_family != "Windows"
    - ansible_os_family != "Gentoo"
  tags: install

- name: Install auditbeat apt (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "auditbeat={{ auditbeat_service.version }}"
    state: present
  when: ansible_os_family == "Debian"
  tags: install

- name: Install auditbeat yum (REHL/CentOS)
  ansible.builtin.yum:
    name: "auditbeat-{{ auditbeat_service.version }}"
    state: present
  when: ansible_os_family == "RedHat"
  tags: install

# INFO: Based on where and how you generate your auditbeat portage package, you may need to change the package name
- name: Install auditbeat portage (Gentoo)
  community.general.portage:
    package: "{{ auditbeat_portage.package }}"
    getbinpkg: "{{ auditbeat_portage.getbinpkg }}"
  when: ansible_os_family == "Gentoo"
  tags: install

- name: Create auditbeat configuration file (Linux)
  ansible.builtin.template:
    src: auditbeat.yml.j2
    dest: "{{ auditbeat_service.config_path }}/auditbeat.yml"
    mode: "0755"
  when: ansible_os_family != "Windows"
  notify: restart-auditbeat
  tags: configure

- name: Install auditing rules for auditbeat (Linux)
  ansible.builtin.copy:
    src: files/{{ auditbeat_service.rule_file }}
    dest: "{{ auditbeat_service.config_path }}/audit.rules.d/"
    owner: root
    group: root
    mode: '0644'
  tags: configure
  when:
    - ansible_os_family != "Windows"
    - auditbeat_service.install_rules
  notify: restart-auditbeat
